#!/bin/sh
# pgscratch -- create a transient scratch postgres instance.
# maximally optimized for a single user on a personal box.
# assumes you have installed postgres.

D=/tmp/myscratch.$$
trap "rm -rf $D;echo;echo $D cleaned up, bye" INT
mysqld --initialize-insecure --datadir=$D
(sleep 1; echo "

THIS IS A SCRATCH MYSQL INSTANCE.
IT WILL BE DESTROYED WHEN YOU EXIT.

mysql -u root

")&
mysqld --datadir=$D --console
