#!/bin/sh
#
# pgwatch -- dumb "IDE-like" sql testing
# usage: pgwatch [-e] [sql-file] [db-file] [duckdb-executable]
#
# Run this in one window, edit a sql file in another window.  You can have
# several queries/commands separated by semicolons.
#
# When you save the sql file, see the results here.
#
# examples:
#   pgwatch mytest.sql mygolden.timedb  # specify both sql file and db-file
#   pgwatch mytest.sql                  # fresh in-memory db only
#
#   .echo on  ->  \set echo ALL
#   .echo off ->  \unset echo
#   .quit     ->  \quit
#
# IDEAS:
# - create scratch db for each run, so each run is stateless as per duckdb
#    CREATE DATABASE my_test_db;
#    \c my_test_db;
#    \c postgres;
#    DROP DATABASE my_test_db;

trap 'exit 0' INT

if [[ $1. = -e. ]]; then
    shift
    START_EDITOR=1
else
    START_EDITOR=0
fi

SQLFILE=${1:-/tmp/duckwatch.sql}
### assume started by pgscrath for now...PGURL=${2:-postgresql://localhost:5432/postgres}

dosum () {
  stat -sL $1|awk '{print $10}'
}

touch $SQLFILE

SIG=$((cat $SQLFILE;echo xxxxxxxxxxxx)|
	od -j 8 -N 4 -t x4|awk 'NR==1 {print $2}')

if [[ $SIG = 4b435544 ]]; then # KCUD
    echo error: your sql file looks like a duckdb file: $SQLFILE 1>&2
    exit 1
fi

if [[ $SIG = 616d726f ]]; then # amro
    echo error: your sql file looks like sqlite file: $SQLFILE 1>&2
    exit 1
fi

if [[ $START_EDITOR -eq 1 ]]; then
    export SQLFILE
    osascript -e 'tell app "Terminal" to do script "cd '$(pwd)'; vi '${SQLFILE}';exit"' 
fi

oldsum=$(dosum $SQLFILE)

while true; do

  clear
  TMPDB=temp_$RANDOM
  echo psql -f $SQLFILE $TMPDB
  echo --
  ###m4 ~/.time.m4 ~/.time.sql $SQLFILE|$DUCKDB $DBFILE
  createdb $TMPDB
  psql -f $SQLFILE $TMPDB
  dropdb $TMPDB

  # if you are using linux, this may be better
  #     inotifywait -e modify $SQLFILE
  newsum=$(dosum $SQLFILE)
  while [[ $oldsum = $newsum ]]; do
    sleep 1
    newsum=$(dosum $SQLFILE)
  done
  echo refreshing...
  oldsum=$(dosum $SQLFILE)

done
